### ISSUE TITLE
Issue on Sony Devices with FabToolbar

### ISSUE THREAD

**Issue by elroid** [fafaldo/FABToolbar#1]
Having an issue with Sony devices in particular (Z3 & Z3 Compact) where the icon of the fab is not disappearing from the background when expanded. It doesn't happen on a Galaxy Nexus running JellyBean or Nexus 5 running Marshmallow. The video below demonstrates the issue...
http://clients.intohand.com/demo/XperiaProblem.mov

**Comment by elroid** [comment]
Ok, I seem to have solved this issue. I just needed to give the fabtoolbar_toolbar element a background color. I can only assume it stems from the variable nature of android.support.design.widget.FloatingActionButton. There isn't one in the ReadMe example, and it works just fine on Marshmallow without it, so i didn't think it was needed. But I've added it and while i can still see the share icon in the background while the animation is in progress, it gets replaced by the background colour when it stops moving, so it's better than it was at least.

**Comment by fafaldo-zz** [comment]
I am so sorry I didn't reply to your message earlier, but I was a bit busy and couldn't really get my hands on Z3. I tried to reproduce the issue on Z2 and Z4 without success so I was waiting to try it on Z3.
I'm happy you found the solution on your own though, thanks!

**Comment by elroid** [comment]
Thanks for getting back to me. It is better than it was but still is not "fixed". It seems the fab is expanding but the share icon is being treated as part of the background rather than disappearing first. With the fix i mentioned it at least doesn't stay in place once the movement has finished, but you can still see it.
http://clients.intohand.com/demo/XperiaLesserProblem.mov

**Comment by fafaldo-zz** [comment]
I still can't get my hands on Z3 and fail to reproduce the problem. If you encountered it on any other device/sdk configuration please let me know. The best way would be to see it happen inside the emulator, but that's rather unlikely.
It's like the Transition Drawable does not work for some reason, or the empty drawable is not loaded. Do you get any exceptions in the logcat while starting the activity and/or expanding and collapsing toolbar?

Alternatively I can provide a callback method for start/end of animation and a way to disable the animation (just hide the drawable instead). You can then disable the animation altogether or just disable it based on specific vendor/device. But still, that's more like a workaround for now.
