### ISSUE TITLE
Unable to listen to fab click

### ISSUE THREAD

**Issue by androidfanatic** [fafaldo/FABToolbar#10]
Trying to listen to click event on fabtoolbar_fab (FloatingActionButton) to call fabToolbar show() only when some condition is met. 

Problem: My onClickListener isn't getting called when Fab is clicked. 

```
findViewById(R.id.fabtoolbar_fab).setOnClickListener(new View.OnClickListener() {
    @Override public void onClick(View view) {
         Log.d("mlog", "My Click"); // Doesn't trigger
         if ( isLoaded() ) { 
             fabToolbar.show();
         } else {
             showSnackBar("Fetching newsfeed...");
         }
     }
});
```

**Comment by Maradox** [comment]
The `FabToolbarLayout.onLayout` sets the `onClickListener` for the Fab, thus your ClickListener is overwritten. It currently seems there is no easy way to listen/intercept the Fab-click. You could extend the `FloatingActionButton` and provide some logic for handling the click yourself (not the cleanest solution though).

**Comment by fafaldo-zz** [comment]
Done, now, to open FAB you have to call `show();` manually, but that gives you freedom to do whatever you want in OnClickListener.
