### ISSUE TITLE
Why to limit it to API 16 when you can make for earlier APIs?

### ISSUE THREAD

**Issue by hirakchhatbar** [fafaldo/FABToolbar#12]
Hi,
you can use 
if (Build.VERSION.SDK_INT < 16)
                              {
                                fabContainer.getViewTreeObserver().removeGlobalOnLayoutListener(this);
                                fab.setVisibility(VISIBLE);
                            } else {
                                fabContainer.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                                fab.setVisibility(VISIBLE);
                            }
to make it compatible for <16 sdk versions.

**Comment by fafaldo-zz** [comment]
I know, I know. I just sometimes tend to use 16 by default, as I no longer target any earlier versions in my projects. Anyway, my implementation uses new animation API introduced in SDK 11, so I lowered min SDK to next higher value that seemed reasonable - 15 (targeting early releases of the Ice Cream Sandwich and Honeycomb is futile, as nobody uses them anymore).
