### ISSUE TITLE
View IDs constricted

### ISSUE THREAD

**Issue by raylee4204** [fafaldo/FABToolbar#2]
It'd be great if you let the devs use their own ids for the views instead of having them hard coded.

**Comment by fafaldo-zz** [comment]
Would you like it to be xml-based? Like:

```
toolbar="@id/my_toolbar"
fab="@id/my_fab"?
```

Because I really don't want to manually search the view hierarchy and find the views by checking class names or instanceof (like in Google's CoordinatorLayout).
