### ISSUE TITLE
I can't change fab button alignment to left

### ISSUE THREAD

**Issue by MuhammadShaker** [fafaldo/FABToolbar#6]
How to change alignment of fab button to right?

**Comment by fafaldo-zz** [comment]
Do you mean left?

**Comment by MuhammadShaker** [comment]
Sorry, yes I want to change it's alignment to left

**Comment by fafaldo-zz** [comment]
Done, if you want to change alignment to left/right set the alignment property of the FAB itself. If you want to change it to top/bottom change FAB container's attributes.
