### ISSUE TITLE
wrap_content support

### ISSUE THREAD

**Issue by onclicklistener** [fafaldo/FABToolbar#7]
Now the view with id "fabtoolbar_toolbar" does not support wrap_content,which make it's hard to contain a view like edittext in it
![untitled](https://cloud.githubusercontent.com/assets/1744780/12030434/9f33bbde-ae39-11e5-837a-55cfa9eab793.gif)

**Comment by fafaldo-zz** [comment]
So sorry for answering so late, but I've been really busy lately. Done in latest release, but I had some hard time implementing that, so I would appreciate your feedback ;)
