### ISSUE TITLE
Had you find the wrong shadow of fab

### ISSUE THREAD

**Issue by seasonyuu** [fafaldo/FABToolbar#8]
The shadow of fab seems that disappears a part.
That's the screenshot.

![device-2016-01-01-222508](https://cloud.githubusercontent.com/assets/8638535/12071170/260e9192-b0d8-11e5-9a06-ba59e4726581.png)

**Comment by seasonyuu** [comment]
I have a solution in my project which use your library , but if you have a better way , could you tell me ?

**Comment by barkai** [comment]
having the same broken shadow issue, i would like to find out what was your solution:)
@seasonyuu @fafaldo

**Comment by seasonyuu** [comment]
In my repo 'GDUThelper'  you can just watch the ' library ' folder

**Comment by barkai** [comment]
@seasonyuu thank's i look into it

**Comment by fafaldo-zz** [comment]
The problem occurs when the toolbar height is smaller then FAB's. I've just set the `clipChildren` attribute of the whole layout to _false_ to solve the problem.
